### ISSUE TITLE
Display Error with bootstrap 4

### ISSUE THREAD

**Issue by donprecious** [pingcheng/bootstrap4-datetimepicker#1]
These plugin has issue with bootstrap 4, dates dont display

**Comment by pingcheng** [comment]
Hi, thanks for reporting this.

I would look into it when I got free.

**Comment by pingcheng** [comment]
Hi @donprecious, I just did a quick test, it shows all elements without problems.
Could you replicate it in jsfiddle or post your code and screenshot here?
Thanks

**Comment by m1017108** [comment]
Hi @pingcheng , I am also unable to see the dates. The datepicker popup is empty.

I tried to copy html code for the datepicker popup which is displayed after clicking the icon as below:
[datepicker-popup.txt](https://github.com/pingcheng/bootstrap4-datetimepicker/files/1935002/datepicker-popup.txt)

I can see some references to 'glyphicon glyphicon-chevron-left' in that code, but bootstrap 4 is not supporting it.

Attaching my html code and screenshot.
[datepicker_code.txt](https://github.com/pingcheng/bootstrap4-datetimepicker/files/1935000/datepicker_code.txt)

<img width="582" alt="screen shot 2018-04-21 at 2 05 03 pm" src="https://user-images.githubusercontent.com/19561522/39088825-04dba5fa-456e-11e8-8cdb-50147ae92211.png">

It would be great if you can look into it.

Thanks

**Comment by m1017108** [comment]
Okay, here's my observation.

1. I installed the package using npm bower
2. I was importing the js and css from 'build' directory
3. Then, I downloaded the code from git and replaced the files in build directory with newly downloaded code.
4. And now, it is showing the dates.

I am new to bower. Do I have to perform any additional steps to use the plugins correctly?

**Comment by pingcheng** [comment]
Hi, @m1017108, thank you for reporting this

This is a forked repo from the original author since he did not update this for bs4, which npm command you used? I did not put the command in the README.md yet.

This repo's npm command is
```
npm i pc-bootstrap4-datetimepicker
```

Could you try with this one? but I will test with bower again thanks
